//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chilaaasg5client.CLServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CLServiceReference.ICLeagueService")]
    public interface ICLeagueService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLeagueService/AddPlayerStat", ReplyAction="http://tempuri.org/ICLeagueService/AddPlayerStatResponse")]
        string AddPlayerStat(string mid, string pid, int goals);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLeagueService/AddPlayerStat", ReplyAction="http://tempuri.org/ICLeagueService/AddPlayerStatResponse")]
        System.Threading.Tasks.Task<string> AddPlayerStatAsync(string mid, string pid, int goals);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLeagueService/ListPlayerStats", ReplyAction="http://tempuri.org/ICLeagueService/ListPlayerStatsResponse")]
        string[] ListPlayerStats(string pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLeagueService/ListPlayerStats", ReplyAction="http://tempuri.org/ICLeagueService/ListPlayerStatsResponse")]
        System.Threading.Tasks.Task<string[]> ListPlayerStatsAsync(string pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLeagueService/ListTeamPoints", ReplyAction="http://tempuri.org/ICLeagueService/ListTeamPointsResponse")]
        string[] ListTeamPoints(string tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLeagueService/ListTeamPoints", ReplyAction="http://tempuri.org/ICLeagueService/ListTeamPointsResponse")]
        System.Threading.Tasks.Task<string[]> ListTeamPointsAsync(string tid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICLeagueServiceChannel : chilaaasg5client.CLServiceReference.ICLeagueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CLeagueServiceClient : System.ServiceModel.ClientBase<chilaaasg5client.CLServiceReference.ICLeagueService>, chilaaasg5client.CLServiceReference.ICLeagueService {
        
        public CLeagueServiceClient() {
        }
        
        public CLeagueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CLeagueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CLeagueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CLeagueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddPlayerStat(string mid, string pid, int goals) {
            return base.Channel.AddPlayerStat(mid, pid, goals);
        }
        
        public System.Threading.Tasks.Task<string> AddPlayerStatAsync(string mid, string pid, int goals) {
            return base.Channel.AddPlayerStatAsync(mid, pid, goals);
        }
        
        public string[] ListPlayerStats(string pid) {
            return base.Channel.ListPlayerStats(pid);
        }
        
        public System.Threading.Tasks.Task<string[]> ListPlayerStatsAsync(string pid) {
            return base.Channel.ListPlayerStatsAsync(pid);
        }
        
        public string[] ListTeamPoints(string tid) {
            return base.Channel.ListTeamPoints(tid);
        }
        
        public System.Threading.Tasks.Task<string[]> ListTeamPointsAsync(string tid) {
            return base.Channel.ListTeamPointsAsync(tid);
        }
    }
}
